### ISSUE TITLE
Passage 2.4 milestone composite p2-repositories are broken

### ISSUE THREAD

**Issue by HannesWell** [eclipse-passage/passage#1091]
The 2.4 milestone/release-candidate repositories are currently broken since they refer to a child named `lac` that does not exist any more. See for example:
https://download.eclipse.org/passage/updates/milestone/2.4.0-RC1/compositeArtifacts.xml

**Comment by ruspl-afed** [comment]
Thank you @HannesWell . I removed "lac" segment  with #1092
