### ISSUE TITLE
Computer.Model and Cpu.Model EnvironmentProperty share family and name

### ISSUE THREAD

**Issue by HannesWell** [eclipse-passage/passage#1096]
The `EnvironmentProperty` implementations `Computer.Model` and `Cpu.Model` both have the same family and name.
This is problematic since `BaseEnvironmentProperty.equals()` only consideres those two values.
Consequently `new Computer.Model().equals(new Cpu.Model())` is true and they cannot be used for different entries in a Map that uses them as keys.

**Comment by eparovyshnaya** [comment]
Thank you, @HannesWell , for the finding.

**Comment by HannesWell** [comment]
Thank you for fixing this.
