### ISSUE TITLE
Operator: get rid of javax.mail dependency

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1147]
We have troubles carrying `javax.mail` dependencies and, as of now, do not have any plans whatsoever to invest any resource in development the side and doughtful feature of sending an issued license by mail from within Operator. 

Get rid of all the codebase, left of the feature, together with the dependency.

**Comment by eparovyshnaya** [comment]
MR #1149

**Comment by ruspl-afed** [comment]
Fixed with #1149
