### ISSUE TITLE
Employ Eclipse Dash license check

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#1161]
Let's try to automate 3rd party license check

**Comment by HannesWell** [comment]
If you are interested, I created a re-usable GH-workflow that requires almost no setup and allows to request license-vetting interactively by commenting on the PR:
https://github.com/eclipse/dash-licenses/tree/master/.github

You can see it for example in M2E:
https://github.com/eclipse-m2e/m2e-core/blob/master/.github/workflows/licensecheck.yml
But it is also used in the Platform-Aggregator and in Tycho.
Besides the workflow you only have to ask the EF-Infra team for a IP-Lap token for passage, just like in:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1464

**Comment by ruspl-afed** [comment]
Done with #1162
