### ISSUE TITLE
Employ Jenkins pipeline

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#1167]
Using GitHub Actions for build does not allow to check steps that requires EF infra like signing

Let's try to employ Jenkins pipeline on EF side

**Comment by HannesWell** [comment]
The Jenkins pipeline in the repo can also be used to deploy (and sign) a snapshot on each push to the master branch, for example we do this in m2e: 
https://github.com/eclipse-m2e/m2e-core/blob/7b340f774365df15715a92f87ca81bad2bc8a0e0/Jenkinsfile#L68-L97

Of course the jar- and pgp-signing has to be done in that pipeline too.

But having the pipeline in the repo makes it simpler to understand than a configuration in Jenkins freestyle/pipeline jobs.

**Comment by ruspl-afed** [comment]
Do you suggest to add deploy stage to https://github.com/eclipse-passage/passage/blob/master/Jenkinsfile ?

**Comment by HannesWell** [comment]
> Do you suggest to add deploy stage to https://github.com/eclipse-passage/passage/blob/master/Jenkinsfile ?

Yes. For m2e we deploy a snapshot after each master build so one can try out a change about 20min after it has been merged.
Of course the jar/pgp signing has to be done then in the pipeline too. The M2E pipeline contains all of that.

If you are interested I can provide a PR to enhance the Jenkins pipeline and implement this.
If not already present you have the Eclipse infra team has to be asked to add the PGP secrets to this repo.

**Comment by ruspl-afed** [comment]
Now it is working, see https://ci.eclipse.org/passage/job/Eclipse%20Passage/job/passage/
