### ISSUE TITLE
"Import Licenses" wizard should support import from archive

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#1191]
"Import Licenses" wizard requires to point to a folder, that typically recieved from outside in the form of archive.

It would be great to recognize licensing information from unpacked archive directly,

**Comment by eparovyshnaya** [comment]
At least (or even rather) we should supply a way to particpate in this part of ui so passage-integrating project could define for themselves how they prefer to gain a license file from end user

**Comment by eparovyshnaya** [comment]
`ImportLicenseDialog` is extended with proper hooks, as well as all the chain of inclusions that make your custom dialog work.

 - construct you verion of `ImportLicenseDialog` with custom `LicenseFilesControl` implementation (read license files from archive, for instance). 
 - supply it to `LicenseStatusDialog` by defining your own version of `BaseLicenseStatusDialog`
 - supply your version of `BaseLicenseStatusDialog` to your version of `BaseEquinoxPassageUI`
 - which you can directly invoke from your own version of `E4LicensingAddon` or other places

**Comment by eparovyshnaya** [comment]
result could be looking like, for instance. that: 
![image](https://github.com/eclipse-passage/passage/assets/3014730/3fec7dec-f12e-4629-a47f-5f2d110f13aa)
