### ISSUE TITLE
Import License should distribute results of import according to licensed functionality

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#1192]
**Steps to reproduce:**
* There is a library L and a product P under licensing
* "Import License" consumes license for L `L.licen` and license for P `P.licen` from the given folder

**Expected:**
* "Import License" puts `L.licen` to L location and `P.licen` to P location 
* L features avaialble

**Actual:**
* "Import License" puts both `L.licen` and `P.licen` to P location a
* L features not available

**Comment by eparovyshnaya** [comment]
The case appeared to be caused be incorrect license pack supplied - it contained two licenses, but both for the product. 

If pack contains 
 - a license for `L` and 
 - a license for `P`

then both 
 - are successfully read: ImportDialog exposes combined set of grants
 - and imported into two dedicated folders

`P` then runs successfully and all covered `L` features are available.
