### ISSUE TITLE
Migration of legacy models keeps unsupported features alive

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1214]
which causes their's migration on each load. 

In case the model is then saved, migrated elements multiply.

**Comment by eparovyshnaya** [comment]
Fixed with #1216

**Comment by ruspl-afed** [comment]
https://github.com/eclipse-passage/passage/pull/1216 is not yet merged

**Comment by ruspl-afed** [comment]
https://github.com/eclipse-passage/passage/pull/1216 is merged
