### ISSUE TITLE
Unnecessary API Compatibility check

### ISSUE THREAD

**Issue by zelenyhleb** [eclipse-passage/passage#1233]
In some bundles we have these lines in .settings:
```
incompatible_api_component_version_include_major_without_breaking_change=Disabled
incompatible_api_component_version_include_minor_without_api_change=Disabled
incompatible_api_component_version_report_major_without_breaking_change=Error
incompatible_api_component_version_report_minor_without_api_change=Error
```

Two last entries cause errors for some bundles even after initial project workspace configuration. 
![image](https://github.com/eclipse-passage/passage/assets/15957500/03650ebd-018c-4fd0-9beb-fdde40c339e2)

As far as I know, bundle versions in Passage Project are incremented all together, i. e. all bundle versions should be the same for the whole codebase. So, do we really need these checks? My proposal is to disable them as well as the first two entries to have initial project configuration clean. WDYT, @eparovyshnaya @ruspl-afed?

**Comment by eparovyshnaya** [comment]
Indeed, if we are intended to keep incrementing all versoions simultneousely, we''ll face these errors each time. 
Vote in favour of disabling the check. 
Will need another one though, to ensure all bundle version are incremented properly.
