### ISSUE TITLE
Provide script to check license headers

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#128]
We spent good time normalizing license headers, we need to employ a script to control its state

**Comment by eparovyshnaya** [comment]
base library is under development in [ArSysOp/liho](https://github.com/arsysop/liho)

**Comment by eparovyshnaya** [comment]
LiHo has been [released](https://mvnrepository.com/artifact/ru.arsysop.liho/liho/0.1)

**Comment by eparovyshnaya** [comment]
[liho-gradle-plugin] is [released](https://github.com/arsysop/liho-gradle-plugin/releases/tag/v0.1)
