### ISSUE TITLE
preferredEvaluationType not getting saved 

### ISSUE THREAD

**Issue by DeepikaKondajji** [eclipse-passage/passage#1302]
This problem is only if I want to generate license for more than one user one after another. It works for the first user but I get an error for the second user. Then I manually add this in the user doc before generating a license - preferredEvaluationType="hardware"

**Comment by eparovyshnaya** [comment]
Thanks, @DeepikaKondajji 
Will take care of this

**Comment by eparovyshnaya** [comment]
fixed
