### ISSUE TITLE
Misprints in licensing requirement level should be treated as fatal

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#1330]
Define product startup requirement like
> Provide-Capability: licensing.feature;licensing.feature="my.product";name="My Product";version="1.0.0";provider="Me";agreements="licenses/EULA.txt";level="**warn**"

Here we have `warn` level instead of `warning`

Actual:
No check at all

Expected:
Let's treat as `fatal`

**Comment by eparovyshnaya** [comment]
@ruspl-afed 
Actually we [already treat](https://github.com/eclipse-passage/passage/blob/master/bundles/org.eclipse.passage.lic.api/src/org/eclipse/passage/lic/api/restrictions/RestrictionLevelComparator.java) anything unknown as _more severe than fatal_. 

And I cannot observe described behavior. 
Can there be any other reason for the case, or some other significant detail to the scenario?

**Comment by eparovyshnaya** [comment]
remove 'high priority' label as it appears to be minor disfunction
