### ISSUE TITLE
Remove RO descriptors layer

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-passage/passage#1346]
Practice shows that there is no decent life outside of EMF (many thanks to @merks again!)

For the very theoretical use case where Passage will be filled with licensing metadata from non-EMF sources, it looks more reasonable to create EMF objects upon such a data first and then business as usual.

For the sensitive licensing data we already have OOP-style implementation.

So, let's remove excessive RO descriptors layer and use EMF directly.

**Comment by eparovyshnaya** [comment]
Many thanks, @ruspl-afed !
