### ISSUE TITLE
Delete marker interface Gear

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1372]
Notion of `Gear` was intended to supply a passage-related product with passage core services for this product's needs. 

Appropriate interface was created in `lic.api` and used by both examplary passage-related products: FLS and Licensing Operator. 

Practice shows that while notion itself is useful (yet questionable), the interface is fruitless. Each product has its own evolution and own way of getting, using, ungetting services, own set of services. Products are not intended to be alike in any sense.

Thus, `Gear` interface just lays a burden, introduces unnecessary connection - and brings noting useful to a product. 

`Gear` and its supplier interfaces are subject for removal.

**Comment by ruspl-afed** [comment]
Missed `since 3.0` annotation for GearAware

**Comment by eparovyshnaya** [comment]
All gear-related services must also be removed from public API.

**Comment by ruspl-afed** [comment]
> All gear-related services must also be removed from public API.

Oops, reopened again
