### ISSUE TITLE
[LOC] OSGi EventListener not usable like LicensePackIssueListener

### ISSUE THREAD

**Issue by HannesWell** [eclipse-passage/passage#1399]
Using an OSGi EventListener registered (e.g. as DS component) for the topics
- `org/eclipse/passage/loc/api/OperatorLicenseEvents/decodedIssued`
- `org/eclipse/passage/loc/api/OperatorLicenseEvents/encodedIssued`

is not as powerful as registering an `LicensePackIssueListener` as Eclipse Extension for two reasons:
- Events are processed asynchronously (`EventAdmin.postEvent()` vs `EventAdmin.sendEvent()`)
- Evens are only fired for personal licenses, not floating licenses

If both points are implemented, using an OSGi `EventListener` can even be more powerful since the `decodedIssued` event is fired before the the encoding happens, which allows to enhance the issued decoded license file before it is encoded. This can for example be used to issue Passage 2 complaint files with Passage 3.

**Comment by eparovyshnaya** [comment]
Irrenevant as LOC sample project has been shut down.
