### ISSUE TITLE
LOC: evolve to reduce maintenance cost

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1403]
Eclipse Passage Operator is a demo application which only purpose is to easily issue a licance for Passage to illustrate its power. Operator is not a part of SimRel and does not affect design or functionality of Passage Core libraries. 

In the current state of soucebse its functionality appears to be attractive for reuse despite it was not designed in a reusable way and is not going to evlove there. 
Also, the application UX is reported to be too complex for a license issuing demo. 

Reuse demands and even simple by-release support evoke pressure on Eclipse Passage project resources, which are scarce as they are.

Scope of this epic-task is to take measures to reduce Operator functionlity to minimize by-release support effort in context of keeping main demonstrative goal tackled.

**Comment by ruspl-afed** [comment]
I need to add that Passage Operator should not depend on ECP/EMFForms, since [this excellent functionality is not a part of SimRel anymore](https://github.com/eclipse-simrel/simrel.build/pull/315) and statistically, this is not a positive sign.

**Comment by eparovyshnaya** [comment]
LOC project has been shut down.
