### ISSUE TITLE
Unsigned content contributed to SimRel

### ISSUE THREAD

**Issue by merks** [eclipse-passage/passage#1425]
I noticed that passage is contributing unsigned content which ends up being PGP signed by simrel-bot, e.g.,

https://download.eclipse.org/releases/2024-09/202408231000/buildInfo/archive/download.eclipse.org/releases/2024-09/202408231000/index/org.eclipse.passage.ldc.feature.feature.jar_3.1.0.v20240821-1851.html

![image](https://github.com/user-attachments/assets/ba8845b0-fd3d-4b6a-9039-5f86ad5dcf6d)

You should review your processes.  Don't ever promote a bundle with unsigned content to download.eclipse.org...

**Comment by ruspl-afed** [comment]
Sorry for this. 
May be this is a side effect of my failed attempt to employ JustJ p2 publisher for Passage. 
I still have no clue what can be wrong in my configuration https://github.com/eclipse-passage/passage/blob/master/sites/org.eclipse.passage.repository/pom.xml. Unfortunately it does not report details of failure (which dependency is missed) even with all the debug options enabled.

**Comment by merks** [comment]
Probably not related...

In any case, you have hit a problem here that took me **forever** to figure out.  I need to change the documentation so that no one else is bitten.  The nasty thing is that whatever logic process the content of `<appArgLine>...</appArgLine>` is stupid and does not handle \t characters properly as plain old white space creating total confusion.

So if you are going to use a formatter,  surround the arguments with `<![CDATA[  ]]>` like here:

![image](https://github.com/user-attachments/assets/ac64c364-b164-415a-a7a2-4dba24a98937)

Then the formatter won't touch the content.  Of course no \t within the content.

**Comment by ruspl-afed** [comment]
Thank you so much Ed @merks for this hint! I have several projects where JustJ just works, but many months I was unable to find notable difference in configuration. It was ready to took **forever**, but you saved all of us!

**Comment by merks** [comment]
You're welcome.  It's beyond annoying because it's whitespace so you of course you don't even see it and who would guess the problem could be so stupid!

**Comment by ruspl-afed** [comment]
>  JustJ  - just works!

Ooops, looks like a product slogan :)

**Comment by ruspl-afed** [comment]
Interesting. When I try to build nightly it [says](https://ci.eclipse.org/passage/job/eclipse-passage/job/passage/job/master/37/console)
```
org.eclipse.core.runtime.AssertionFailedException: assertion failed: The folder '/home/jenkins/agent/workspace/eclipse-passage_passage_master/sites/org.eclipse.passage.repository/target/passage-sync/updates/milestone' is an empty composite. You must do at least one milestone build.
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:119)
	at org.eclipse.justj.p2.P2Manager.cleanMilestoneComposite(P2Manager.java:408)
```
and when I try to build milestone it [says](https://ci.eclipse.org/passage/job/eclipse-passage/job/passage/job/master/36/console) 
```
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/home/jenkins/agent/workspace/eclipse-passage_passage_master/sites/org.eclipse.passage.repository/target/passage-sync/updates/nightly.
```

Do you think I have a chance to start from non-empty https://download.eclipse.org/passage/updates/ or I should think about another URL @merks ?

**Comment by ruspl-afed** [comment]
I managed to apply a trick: manually upload p2 content to "milestones" folder in a form it expects. Now I have the very first nightly build published here https://download.eclipse.org/passage/updates/

**Comment by merks** [comment]
Sorry, I lost track of your request.  yes, the fact that there is a release but there was no milestone was unexpected.  The release folders being composites is maybe problematic.

---

You know that if you move some from download.eclipse.org to archive.eclipse.org that there is an automatic 404 redirect from download.eclipse.org to archive.eclipse.org, so moving content doesn't generally break the URLs and p2 will continue to work following the redirect...

**Comment by ruspl-afed** [comment]
@merks I did a contribution to SimRel from https://download.eclipse.org/passage/updates/milestone/S202408280821/index.html
Please let me know if it looks good from your PoV and we can close this one

**Comment by merks** [comment]
Yes, it looks good now.  Thanks.  🥇
