### ISSUE TITLE
Remove code unused by LIC and LCD

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#1430]
Runtime Passage component (LIC) currently contains several bundles and features that Passage Runtime does not actually use. 
Like feature _users_, _products_, _features_; _keys_ an _agreements_ are also  to be analyzed. 

LCD functionality is to be kept sufficiently facilitated though, so code revision should be performend with LCD needs in mind.

**Comment by eparovyshnaya** [comment]
bundles `e4.*` and `lic.jface.*` are yet to be considered

**Comment by ruspl-afed** [comment]
Done
