### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by uzairb1** [eclipse-passage/passage#263]
Need documentation on how to generate and validate licenses in Eclipse Passage

**Comment by eparovyshnaya** [comment]
Issues to track
- [ ] [564528](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564528) _define_  phase
- [ ] [564530](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564530) _define_ in Operator 
- [ ] [564540](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564540) _compile_ phase
- [ ] [564541](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564541) _operate_ phase: meta-information
- [ ] [564542](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564542) _operate_: issue license
- [ ] [564543](https://bugs.eclipse.org/bugs/show_bug.cgi?id=564543)  explain runtime of a licensed application

**Comment by eparovyshnaya** [comment]
available at [passage-docs](https://eclipse-passage.github.io/passage-docs/) GitHub Pages
