### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by uzairb1** [eclipse-passage/passage#265]
We are students and are doing a project to compare available different licensing frameworks. To do this we downloaded each framework and read its code and the documentation provided with each of them, and we are currently close to completing this project, the submission deadline is in 3 weeks and it seems like the documentation will not be ready in this time period by you.
Due to missing documentation it is very difficult to implement Passage. We have to hand in our project in three weeks, so we asume the documentation will not be ready until this deadline.
Do you have an example Eclipse Plugin implementation, where we can see the source code and play with all features of Passage?

**Comment by uzairb1** [comment]
Thank you very much in advance

**Comment by eparovyshnaya** [comment]
When you create a new _Plug-in Project_  in Eclipse, there is a way to use one of available templates. 

If you chose `Rich Client Application`  for your new _Plug-in Project_, Passage templates become available. Use `Licensed RCP 4.x (minimal)`, it creates an RCP product with general licensing protection. Launch generated `.product` _as Eclipse Application_ and you'll see informative Licensing Status dialog as the result of startup application license check.

**Comment by ruspl-afed** [comment]
Please note that you need to use "Eclipse IDE for RCP and RAP Developers" to see the templates mentioned above.

**Comment by eparovyshnaya** [comment]
Documentation is going to be delivered in the scope of #263
