### ISSUE TITLE
Runime:  upgrade OSHI library

### ISSUE THREAD

**Issue by eparovyshnaya** [eclipse-passage/passage#947]
Cosider upgrade to newer OSHI lib version.

-------------------
Version: 1.1.0 
Ported from [bugs.eclipse.org: 569785](https://bugs.eclipse.org/bugs/show_bug.cgi?id=569785)

**Comment by ruspl-afed** [comment]
Let's try to find an OSHi version that works well with notarized [JNA 5.13.0](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L45)
see https://github.com/eclipse-orbit/orbit-simrel/issues/7

**Comment by ruspl-afed** [comment]
Fixed with #1250
